# Generated by Django 3.2.5 on 2021-07-21 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expert_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_file', models.FileField(upload_to='images/expert/map_files', verbose_name='فایل نقشه')),
                ('tiff_file', models.FileField(upload_to='geospatial_files/expert/tiff_files', verbose_name='فایل نقشه')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان نقشه')),
                ('expert', models.CharField(default='سحاب مومنی', max_length=300, verbose_name='نام کارشناس')),
                ('date', models.DateField(verbose_name='تاریخ حادثه')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('P', 'در حال بررسی'), ('B', 'نیاز به اصلاحات دارد')], default='P', max_length=1, verbose_name='وضعیت')),
                ('description', models.TextField(blank=True, help_text='توضیحات نقشه', null=True, verbose_name='توضیحات')),
            ],
        ),
    ]
