# Generated by Django 3.2.5 on 2021-07-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert_panel', '0001_initial'),
        ('manager_panel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert_map',
            name='disaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_panel.disaster', verbose_name='نام مخاطره'),
        ),
        migrations.AddField(
            model_name='expert_map',
            name='event',
            field=models.ForeignKey(blank=True, help_text='آیا این نقشه زیر مجموعه یک رخداد است؟', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_panel.event'),
        ),
    ]
