# Generated by Django 3.2.5 on 2021-07-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_panel', '0003_alter_expert_map_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_map',
            name='date',
            field=models.DateField(verbose_name='تاریخ حادثه'),
        ),
        migrations.AlterField(
            model_name='expert_map',
            name='tiff_file',
            field=models.FileField(upload_to='geospatial_files/expert/tiff_files', verbose_name='فایل تیف'),
        ),
    ]
