# Generated by Django 3.2.5 on 2021-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_panel', '0005_alter_expert_map_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_map',
            name='status',
            field=models.CharField(choices=[('P', 'در حال بررسی'), ('B', 'نیاز به اصلاحات دارد'), ('O', 'تایید شده است')], default='P', max_length=1, verbose_name='وضعیت'),
        ),
    ]
