# Generated by Django 3.2.7 on 2021-09-23 15:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdms', '0008_auto_20210923_1235'),
        ('expert_panel', '0007_auto_20210923_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_map',
            name='tiff_file',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gdms.geospatialfile'),
        ),
    ]
