# Generated by Django 3.2.7 on 2021-10-14 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_panel', '0008_alter_expert_map_tiff_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_map',
            name='disaster',
            field=models.CharField(max_length=50, verbose_name='نام مخاطره'),
        ),
    ]
