# Generated by Django 3.2.7 on 2021-11-01 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_panel', '0005_auto_20211101_1028'),
        ('expert_panel', '0009_alter_expert_map_disaster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expert_map',
            name='disaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_panel.disaster', verbose_name='نام مخاطره'),
        ),
    ]
