# Generated by Django 3.2.7 on 2021-11-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expert_panel', '0010_alter_expert_map_disaster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expert_map',
            name='event',
        ),
        migrations.RemoveField(
            model_name='expert_map',
            name='map_status',
        ),
    ]
