# Generated by Django 3.2.7 on 2021-11-23 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_panel', '0011_auto_20211112_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='expert_map',
            name='author',
            field=models.CharField(default='سحاب مومنی', max_length=300, verbose_name='نام نویسنده'),
            preserve_default=False,
        ),
    ]
