# Generated by Django 3.2.7 on 2021-12-10 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('manager_panel', '0005_auto_20211101_1028'),
        ('gdms', '0012_alter_geospatialfile_options'),
        ('expert_panel', '0012_expert_map_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Draw_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sat', models.CharField(max_length=300, verbose_name='نام ماهواره تصویر')),
                ('disaster_date', models.DateField(verbose_name='تاریخ حادثه')),
                ('image_date', models.DateField(verbose_name='تاریخ اخذ تصویر')),
                ('proccess_date', models.DateField(verbose_name='تاریخ پردازش تصویر')),
                ('title', models.CharField(max_length=300, verbose_name='نام ماهواره تصویر')),
                ('total_city', models.IntegerField(verbose_name='تعداد شهرهای تحت تاثیر سیلاب')),
                ('total_vilage', models.IntegerField(verbose_name='تعداد روستاهای تحت تاثیر سیلاب')),
                ('total_hamlet', models.IntegerField(verbose_name='تعداد دهکده های تحت تاثیر سیلاب')),
                ('total_pop', models.IntegerField(verbose_name='جمعیت تحت تاثیر سیلاب')),
                ('description', models.TextField(blank=True, help_text='توضیحات نقشه', null=True, verbose_name='توضیحات')),
                ('export_image', models.FileField(default=None, null=True, upload_to='', verbose_name='فایل نقشه')),
                ('system_name', models.CharField(max_length=300, unique=True, verbose_name='نام  سیستمی')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_panel.disaster', verbose_name='نام مخاطره')),
                ('tiff_file', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gdms.geospatialfile')),
            ],
        ),
    ]
