# Generated by Django 3.2.7 on 2021-12-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_panel', '0013_draw_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw_map',
            name='export_image',
            field=models.FileField(default=None, upload_to='', verbose_name='فایل نقشه'),
        ),
        migrations.AlterField(
            model_name='draw_map',
            name='title',
            field=models.CharField(max_length=300, verbose_name='نام منطقه تحت تاثیر سیلاب '),
        ),
    ]
