# Generated by Django 3.2.7 on 2021-12-12 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expert_panel', '0014_auto_20211210_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draw_map',
            name='export_image',
            field=models.FileField(default=None, upload_to='images/draw_map/image_export', verbose_name='فایل نقشه'),
        ),
        migrations.AlterField(
            model_name='draw_map',
            name='system_name',
            field=models.CharField(blank=True, max_length=300, unique=True, verbose_name='نام  سیستمی'),
        ),
    ]
