export const DrawMapData_IMPOERT_SUCCESS = 'DrawMapData_IMPOERT_SUCCESS'
export const DrawMapData_IMPOERT_FAIL = 'DrawMapData_IMPOERT_FAIL'
export const DrawMapData_IMPOERT_RESET = 'DrawMapData_IMPOERT_RESET'
export const DrawMap_INSERT_RESET = 'DrawMap_INSERT_RESET'
export const DrawMap_INSERT_SUCCESS = 'DrawMap_INSERT_SUCCESS'
export const DrawMap_INSERT_FAIL = 'DrawMap_INSERT_FAIL'