# Generated by Django 3.2.6 on 2021-09-16 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Geoserver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_address', models.CharField(default='http://localhost:8080/geoserver/', max_length=300, verbose_name='آدرس دامنه')),
                ('user_name', models.CharField(default='admin', max_length=30, verbose_name='نام کاربری')),
                ('password', models.CharField(default='geoserver', max_length=30, verbose_name='گذرواژه')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('system_name', models.CharField(max_length=30, unique=True, verbose_name='نام سیستمی')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('geoserver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdms.geoserver', verbose_name='سرور نقشه')),
            ],
        ),
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('system_name', models.CharField(max_length=30, unique=True, verbose_name='نام سیستمی')),
                ('description', models.TextField(blank=True, help_text='توضیحات استایل', verbose_name='توضیحات')),
                ('file_path', models.FileField(upload_to='geospatialFile/Styles/', verbose_name='فایل')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdms.workspace', verbose_name='فضای کار')),
            ],
        ),
        migrations.CreateModel(
            name='GeospatialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام فایل')),
                ('system_name', models.CharField(max_length=30, unique=True, verbose_name='نام سیستمی')),
                ('file_path', models.FileField(upload_to='geospatialFile/geospatials/', verbose_name='فایل')),
                ('file_type', models.CharField(blank=True, max_length=30)),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیحات')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('style', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='gdms.style', verbose_name='استایل')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gdms.workspace', verbose_name='محیط کاری در سرور')),
            ],
        ),
    ]
