# Generated by Django 3.2.7 on 2021-09-19 07:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdms', '0002_alter_style_file_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='geospatialfile',
            old_name='file_path',
            new_name='file',
        ),
    ]
