# Generated by Django 3.2.7 on 2021-09-19 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdms', '0003_rename_file_path_geospatialfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialfile',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gdms.style', verbose_name='استایل'),
        ),
    ]
