# Generated by Django 3.2.7 on 2021-09-22 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdms', '0006_auto_20210922_2359'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='geospatialfile',
            name='is_on_geoserver',
        ),
    ]
