# Generated by Django 3.2.7 on 2021-09-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdms', '0007_remove_geospatialfile_is_on_geoserver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialfile',
            name='file_type',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='geospatialfile',
            name='system_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام سیستمی'),
        ),
        migrations.AlterField(
            model_name='style',
            name='system_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام سیستمی'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='system_name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام سیستمی'),
        ),
    ]
