# Generated by Django 3.2.7 on 2021-11-04 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdms', '0009_alter_workspace_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geospatialfile',
            name='name',
            field=models.CharField(max_length=100, unique=True, verbose_name='نام فایل'),
        ),
    ]
