# Generated by Django 3.2.7 on 2021-11-04 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdms', '0010_alter_geospatialfile_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geospatialfile',
            options={'verbose_name': 'فایل مکنی'},
        ),
    ]
