# Generated by Django 3.2.7 on 2021-11-12 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gdms', '0011_alter_geospatialfile_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geospatialfile',
            options={'verbose_name': 'فایل مکانی'},
        ),
    ]
