# Generated by Django 3.2.5 on 2021-07-21 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('expert_panel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fa_name', models.CharField(max_length=50, verbose_name='نام فارسی')),
                ('en_name', models.CharField(max_length=50, verbose_name='نام انگلیسی')),
                ('abbreviation', models.CharField(max_length=50, verbose_name='نام مخفف')),
            ],
        ),
        migrations.CreateModel(
            name='Manager_feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('R', 'رد شدن'), ('B', 'نیاز به اصلاحات دارد'), ('O', 'تایید شده')], max_length=1, verbose_name='وضعیت')),
                ('expert', models.CharField(default='sahab momeni', max_length=100, verbose_name='نام کارشناسان')),
                ('manager', models.CharField(default='sahab momeni', max_length=100, verbose_name='نام مدیر ')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='تاریخ بررسی')),
                ('feedback', models.TextField(blank=True, help_text='توضیحات ', null=True, verbose_name='توضیحات')),
                ('expter_map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='expert_panel.expert_map')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان رخداد')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='تاریخ پایان')),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True, help_text='معرفی رخداد', null=True, verbose_name='توضیحات')),
                ('disater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_panel.disaster')),
            ],
        ),
        migrations.CreateModel(
            name='Approved_map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_name', models.CharField(default='uname', max_length=50)),
                ('expert', models.CharField(default='sahab momeni', max_length=100, verbose_name='نام کارشناسان')),
                ('manager', models.CharField(default='sahab momeni', max_length=100, verbose_name='نام مدیر تایید کننده')),
                ('img_file', models.FileField(upload_to='images/system/map_files', verbose_name='فایل نقشه')),
                ('tiff_file', models.FileField(upload_to='geospatial_files/system/tiff_files', verbose_name='فایل نقشه')),
                ('title', models.CharField(max_length=300, verbose_name='عنوان نقشه')),
                ('date', models.DateField(verbose_name='تاریخ حادثه')),
                ('pub_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(blank=True, help_text='توضیحات نقشه', null=True, verbose_name='توضیحات')),
                ('disaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manager_panel.disaster', verbose_name='نام مخاطره')),
                ('event', models.ForeignKey(blank=True, help_text='آیا این نقشه زیر مجموعه یک رخداد است؟', null=True, on_delete=django.db.models.deletion.CASCADE, to='manager_panel.event')),
            ],
        ),
    ]
