# Generated by Django 3.2.5 on 2021-07-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_panel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approved_map',
            name='manager',
            field=models.CharField(default='younes dehghan', max_length=100, verbose_name='نام مدیر تایید کننده'),
        ),
    ]
