# Generated by Django 3.2.5 on 2021-07-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager_panel', '0002_alter_approved_map_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager_feedback',
            name='manager',
            field=models.CharField(default='younes dehghan', max_length=100, verbose_name='نام مدیر '),
        ),
    ]
