# Generated by Django 3.2.7 on 2021-09-23 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gdms', '0008_auto_20210923_1235'),
        ('manager_panel', '0003_alter_manager_feedback_manager'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='workspace',
            field=models.ForeignKey(default=17, on_delete=django.db.models.deletion.SET_DEFAULT, to='gdms.workspace'),
        ),
    ]
