# Generated by Django 3.2.7 on 2021-10-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210925_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccounts',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='is_expert',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='is_manager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='is_staff',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='is_superuser',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='useraccounts',
            name='is_topmanager',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
