"""
Django settings for ISA_RapidMapping project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
import sys
from datetime import timedelta

import socket

try:
    HOSTNAME = socket.gethostname()
except:
    HOSTNAME = 'localhost'
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

version_number = 0.01

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-559d+7)4w6bqblgh!27w-@!ei(w^i5#(oo#sf_wj=r4ogc)=6j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",'localhost']

CORS_ALLOW_ALL_ORIGINS = True

# CORS_ORIGIN_ALLOW_ALL = True

# CORS_ORIGIN_WHITELIST = (
#     'http://localhost:8000',
#     'http://127.0.0.1:8000',
#     'http://localhost:8080',
#     'http://127.0.0.1:8080',
# )

# CORS_URLS_REGEX = r"^/api/.*$"
# Application definition
SESSION_SERIALIZER = 'django.contrib.sessions.serializers.PickleSerializer'
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # basic app
    'api',
    'gdms', # geospatial data management system
    'accounts',
    # panel app
    'expert_panel',
    'manager_panel',
    # thrid api
    'rest_framework',
    'corsheaders',
    'bootstrap4',
    'crispy_forms',
    'djoser',
    'rest_framework.authtoken',
    'rest_framework_simplejwt.token_blacklist',
    
]

CRISPY_TEMPLATE_PACK = 'bootstrap4'
REST_FRAMEWORK = {
    'DATETIME_FORMAT': "%Y-%m-%d", 
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES':[
        'rest_framework.permissions.IsAuthenticated'
    ],
    'DEFAULT_PARSER_CLASSES': [
        'rest_framework.parsers.JSONParser',
    ]
}
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'ISA_RapidMapping.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR , 'templates'),],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'ISA_RapidMapping.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.contrib.gis.db.backends.postgis',
        'NAME': 'ISA_RapidMapping',
        'USER': 'postgres',
        'PASSWORD': 'sahab1992',
        'HOST': 'localhost',
        'PORT': '5435',
    }
}
# Email
# moh3en42@gmail.com
BING_MAP_KEY = 'ArZfElosT3_4dDa3poGyONziO_X6_-qzrADW7lU3Rn3-3_t1a6PPyJgMX-pBF4CJ'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
# EMAIL_HOST_USER = 'sahabee92@gmail.com'
# EMAIL_HOST_PASSWORD = 'lkfzeqdkbvebgqvi'
EMAIL_HOST_USER = 'ISARapidMappingWebGIS@gmail.com'
EMAIL_HOST_PASSWORD = 'sahab1992'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
EMAIL_USE_TLS = True
# Auth System
AUTH_USER_MODEL = 'accounts.UserAccounts'

SIMPLE_JWT = {
   'AUTH_HEADER_TYPES': ('JWT',),
   'ACCESS_TOKEN_LIFETIME': timedelta(minutes=60*24),
   'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
}
DJOSER = {
    'LOGIN_FIELD': 'email',
    'USER_CREATE_PASSWORD_RETYPE':True,
    'USERNAME_CHANGED_EMAIL_CONFIRMATION':True,
    'PASSWORD_CHANGED_EMAIL_CONFIRMATION':True,
    'SEND_CONFIRMATION_EMAIL':True,
    'SET_PASSWORD_RETYPE':True,
    'PASSWORD_RESET_CONFIRM_URL': 'password/reset/confirm/{uid}/{token}',
    'USERNAME_RESET_CONFIRM_URL': 'email/reset/confirm/{uid}/{token}',
    'ACTIVATION_URL': 'activate/{uid}/{token}',
    'SEND_ACTIVATION_EMAIL': True,
    'SERIALIZERS': {
        'user_create':'accounts.serializers.UserCreateSerializer',
        'user':'accounts.serializers.UserCreateSerializer',
        'user_delete':'djoser.serializers.UserDeleteSerializer',
    },
    'EMAIL':{
        'activation': 'accounts.views.WebSiteActivationEmail',
    },
}




# email: sahabee92@gmail.com
# passwprd: uaxiydidzpfqhyrg
# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]



# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'fa'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    
]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

#### WebGIS conf

GEOSERVER_URL = 'http://localhost:8080/geoserver/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
VENV = sys.prefix
OSGEO_VENV = os.path.join(VENV,'Lib\site-packages\osgeo')
# print(OSGEO_VENV)
GEOS_LIBRARY_PATH = os.path.join(OSGEO_VENV , 'geos_c.dll')
GDAL_LIBRARY_PATH = os.path.join(OSGEO_VENV , 'gdal302.dll')
os.environ['GDAL_DATA'] =  os.path.join(OSGEO_VENV , 'data\gdal')
os.environ['PROJ_LIB'] =   os.path.join(OSGEO_VENV , 'data\proj')
# print(os.environ['GDAL_DATA'])
os.environ["PATH"] += os.pathsep + str(OSGEO_VENV)


# # remove migrations 
# python manage.py migrate admin zero
# python manage.py migrate auth zero
# python manage.py migrate contenttypes zero
# python manage.py migrate sessions zero